services:
  - type: web
    name: flashcards
    runtime: python
    rootDir: web
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: DATA_FILE
        value: flashcards_data.json
